version: '3.8'

networks:
  pandora:

services:
  web:
    image: php:8.2-apache
    container_name: apache_php
    build: .
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    depends_on:
      - db
    networks:
      - pandora

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pandora

volumes:
  mysql_data:
